# Generated by Django 4.2.6 on 2023-12-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_emp_hiredate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='hiredate',
            field=models.DateField(),
        ),
    ]
